#!/usr/bin/env bash
set -e

cd "$(dirname "$0")"

echo "Building greeting in release mode..."
cargo build --release

# Создаём ~/.local/bin если отсутствует
mkdir -p "$HOME/.local/bin"

echo "Copying binary to ~/.local/bin/greeting"
cp target/release/greeting "$HOME/.local/bin/greeting"

echo ""
echo "✓ Installation complete. Binary is at ~/.local/bin/greeting"
echo ""
echo "────────────────────────────────────────────────────────"
echo "Next steps – configure autostart (choose one):"
echo "Add ~/.local/bin/ to paths or use direct path"
echo ""
echo "1) Systemd (user service) – recommended for most users:"
echo ""
echo "   mkdir -p ~/.config/systemd/user"
echo "   cat > ~/.config/systemd/user/greeting.service <<EOF"
echo "   [Unit]"
echo "   Description=Greeting daemon – updates system data cache"
echo "   After=network-online.target"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   ExecStart=%h/.local/bin/greeting daemon"
echo "   Restart=on-failure"
echo ""
echo "   [Install]"
echo "   WantedBy=default.target"
echo "   EOF"
echo ""
echo "   systemctl --user daemon-reload"
echo "   systemctl --user enable --now greeting.service"
echo ""
echo "2) Hyprland (add to hyprland.lua):"
echo ""
echo "   hl.exec_cmd("~/.local/bin/greeting daemon")"
echo ""
echo "3) Fish shell (add to config.fish):"
echo ""
echo "   ~/.local/bin/greeting daemon &"
echo ""
echo "After setting up daemon, run once:"
echo "   greeting init      # create config"
echo "   greeting update    # fetch initial data"
echo "   greeting show      # test output"
echo ""
echo "Then add 'greeting' to your shell rc file to show message on terminal start."
